### PR TITLE
Fixes issue #1232

### LINKED ISSUE #1232: Possible incorrect result in debug_getModifiedAccountsByNumber
This curl command:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"debug_getModifiedAccountsByNumber","params": ["0x2dcaa9", "0x2dcaaa"],"id":64}' -H "Content-Type: application/json" http://localhost:8545
```

(`0x2dcaa9` is block 3001001) returns this data:

```
{
  "id": 64,
  "jsonrpc": "2.0",
  "result": [
    ....
    "0x083696cdfd96f9af4fb5347d82538ef0e617fe8e",
    ....
  ]
}
```

The trouble is, according to Etherscan (and TrueBlocks) account `0x083696cdfd96f9af4fb5347d82538ef0e617fe8e` was not involved in block 3001001, however both ES and TB say it was involved in block 3001002.

I suspect that this is an 'off-by-one' error since the `dbutils.PlainAccountChangeSetBucket` is consulted which I think records changes in the block prior, but I'm not sure.

Perhaps this line needs to add one? https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/rpcdaemon/commands/debug_api.go#L177

### PR DESCRIPTION
**Pull request by tjayrush**
Closes #1232 

See comment: https://github.com/ledgerwatch/turbo-geth/issues/1232#issuecomment-707438492

### CODE REVIEW

File: cmd/rpcdaemon/commands/debug_api.go [hunk 1]
```diff
@@ -118,33 +117,45 @@ func (api *PrivateDebugAPIImpl) AccountRange(ctx context.Context, blockNrOrHash
...
 }
 
-func (api *PrivateDebugAPIImpl) GetModifiedAccountsByNumber(_ context.Context, startNum rpc.BlockNumber, endNum *rpc.BlockNumber) ([]common.Address, error) {
-	if endNum != nil && startNum.Int64() >= endNum.Int64() {
-		return nil, fmt.Errorf("start block height (%d) must be less than end block height (%d)", startNum.Int64(), endNum.Int64())
+// GetModifiedAccountsByNumber returns a list of accounts found in the change sets
+// startNum - first block from which to include results
+// endNum - if present, last block from which to include results (inclusive). If not present, startNum.
+func (api *PrivateDebugAPIImpl) GetModifiedAccountsByNumber(ctx context.Context, startNumber rpc.BlockNumber, endNumber *rpc.BlockNumber) ([]common.Address, error) {
+	tx, err := api.dbReader.Begin(ctx)
```
Comment (AlexeyAkhunov) [inline cmd/rpcdaemon/commands/debug_api.go:124]: I suggest using `tx, err := api.db.Begin(ctx, nil, false)` instead. Second argument is parent (`nil`), third argument is writable (`false`). Otherwise, `Begin` looks like we want a writeable transaction, and only getting a read-only one because we are remote. But if running against local chaindata, it will be actually writeable. Further on in this function, you should try to use `tx` instead of `api.dbReader`

Comment (tjayrush) [reply cmd/rpcdaemon/commands/debug_api.go:124]: This same pattern appears in a lot of other places in the RPC code. Should I change them everywhere?

I can make another issue and PR to track that change or do it as part of this PR if you wish.

File: cmd/rpcdaemon/commands/debug_api.go [hunk 2]
```diff
@@ -118,33 +117,45 @@ func (api *PrivateDebugAPIImpl) AccountRange(ctx context.Context, blockNrOrHash
...
-			return nil, fmt.Errorf("end block %x not found", uint64(endNum.Int64()))
-		}
+	// is endNum too big?
+	if endNum > latestBlock {
+		return nil, fmt.Errorf("end block (%d) is later than the latest block (%d)", endNum, latestBlock)
 	}
 
-	return getModifiedAccounts(api.dbReader, uint64(startNum.Int64()), uint64(endNum.Int64()))
+	// will check that startNum is less or equal to endNum
+	return getModifiedAccounts(api.dbReader, startNum, endNum)
```
Comment (AlexeyAkhunov) [inline cmd/rpcdaemon/commands/debug_api.go:153]: Can you try to change this to pass `tx` too? Do you feel adventurous enough? I can help you. You need to modify `eth.GetModifiedAccounts` function (in `ethdb/walk.go`) from using `Walk` function to use a cursor and for loop instead

File: cmd/rpcdaemon/commands/debug_api.go (hunk 1 above)
Comment (AlexeyAkhunov) [reply cmd/rpcdaemon/commands/debug_api.go]: If you can, yes, as long as there is a way to test this. This may improve performance, because we do not end up opening transactions multiple times

File: cmd/rpcdaemon/commands/debug_api.go (hunk 2 above)
Comment (tjayrush) [reply cmd/rpcdaemon/commands/debug_api.go:153]: I'm totally adventurous. I'll try it now.

Comment (tjayrush) [reply cmd/rpcdaemon/commands/debug_api.go:153]: Should I try to fix it elsewhere as well or make a new PR?

For example, here: https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/rpcdaemon/commands/eth_api.go#L146

Comment (AlexeyAkhunov) [reply cmd/rpcdaemon/commands/debug_api.go:153]: Maybe make a new PR for other things

File: ethdb/walk.go [hunk 3]
```diff
@@ -93,39 +94,43 @@ func (sc *splitCursor) Next() (key1, key2, key3, val []byte, err error) {
...
-	if len(keys) == 0 {
+	if len(changedAddrs) == 0 {
 		return nil, nil
 	}
-	accounts := make([]common.Address, len(keys))
-	idx := 0
 
-	for key := range keys {
-		copy(accounts[idx][:], key[:])
+	idx := uint64(0)
```
Comment (AlexeyAkhunov) [inline ethdb/walk.go:128]: It is better for idx to be just int, so `idx := 0`

File: ethdb/walk.go [hunk 4]
```diff
@@ -93,39 +94,43 @@ func (sc *splitCursor) Next() (key1, key2, key3, val []byte, err error) {
...
 
-		if keyTimestamp > endTimestamp {
-			return false, nil
+	changedAddrs := make(map[common.Address]struct{})
+	startCode := dbutils.EncodeTimestamp(startNum)
+
+	c := tx.Cursor(dbutils.PlainAccountChangeSetBucket)
+	for k, v, err := c.Seek(startCode); k != nil; k, v, err = c.Next() {
+		if err != nil {
+			fmt.Println("Error:", err)
```
Comment (AlexeyAkhunov) [inline ethdb/walk.go:106]: you can do `return nil, fmt.Errorf("iterating over account changeset: %w", err)` to bubble it up

File: ethdb/walk.go [hunk 5]
```diff
@@ -93,39 +94,43 @@ func (sc *splitCursor) Next() (key1, key2, key3, val []byte, err error) {
...
-		keyTimestamp, _ := dbutils.DecodeTimestamp(k)
+// GetModifiedAccounts returns a list of addresses that were modified in the block range
+func GetModifiedAccounts(tx Tx, startNum, endNum uint64) ([]common.Address, error) {
 
-		if keyTimestamp > endTimestamp {
-			return false, nil
+	changedAddrs := make(map[common.Address]struct{})
+	startCode := dbutils.EncodeTimestamp(startNum)
+
+	c := tx.Cursor(dbutils.PlainAccountChangeSetBucket)
```
Comment (AlexeyAkhunov) [inline ethdb/walk.go:103]: Add `defer c.Close()` after this to make sure cursor is closed when we get out of this function (for any reason)

File: ethdb/walk.go [hunk 6]
```diff
@@ -93,39 +94,43 @@ func (sc *splitCursor) Next() (key1, key2, key3, val []byte, err error) {
...
 
 		walker := func(addr, _ []byte) error {
-			keys[common.BytesToAddress(addr)] = struct{}{}
+			changedAddrs[common.BytesToAddress(addr)] = struct{}{}
 			return nil
 		}
-
 		if innerErr := changeset.AccountChangeSetPlainBytes(v).Walk(walker); innerErr != nil {
-			return false, innerErr
+			fmt.Println("Error:", err)
```
Comment (AlexeyAkhunov) [inline ethdb/walk.go:119]: Rename `innerErr` into `err` and `return nil, fmt.Errrof("iterating over account changeset for %k: %w", k, err)`

File: ethdb/walk.go (hunk 3 above)
Comment (tjayrush) [reply ethdb/walk.go]: Thanks for being patient with a rookie...updated.

File: ethdb/walk.go (hunk 5 above)
Comment (tjayrush) [reply ethdb/walk.go:103]: Learning moment...

Question for you. Is this just 'good practice' (in other words, the garbage collector collects it anyway) or will it leak memory or resources like 'C'?

Also, if I forget something like this is there some way to detect it later (other than search)?

Comment (AlexeyAkhunov) [reply ethdb/walk.go:103]: Garbage collector will collect "Golang" objects, but not the "C" objects attached to them. So most objects that are pure Go do not even have `Close` function, but if they do, that usually means you have to call it to free something. In our case, cursors may hold "C" objects (LMDB cursor if we use `--chaindata` in RPC daemon), and therefore have `Close()`

**Comment by AlexeyAkhunov** [comment]
Did you cherry-pick my commits from another branch? I think you should just do these 2 things:
```
git fetch origin
git merge origin/master
```

**Comment by tjayrush** [comment]
> Did you cherry-pick my commits from another branch? I think you should just do these 2 things:
> 
> ```
> git fetch origin
> git merge origin/master
> ```

I'm sorry. I'm lost now. I did `git fetch....etc.` but it just says `Already up to date.`
