### PR TITLE
Fix infinite rpc.gascap on eth_estimateGas

### LINKED ISSUE #1284: eth_estimateGas does not seem to work
This curl command:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params": [{"from": "0x3D597789ea16054a084ac84ce87F50df9198F415","to": "0x3D597789ea16054a084ac84ce87F50df9198F415","value": "0x1"}],"id":1}' localhost:8545
```

always returns

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "gas required exceeds allowance (0)"
  }
}
```

Although the value changes from time to time, Parity returns

```
{
  "jsonrpc": "2.0",
  "result": "0x5208",
  "id": 1
}
```

### PR DESCRIPTION
**Pull request by 3esmit**
Fixes #1284

Cause was that, when adapting the old rpc to the new rpcdaemon, `gasCap != 0` was translated to `gasCap != nil`, however gasCap does not come null by default, it cames as a big Int object initialized with zero value. 

The zero gasCap means infinite gasCap. 

This gascaps are added to ensure that public rpc endpoints cannot be broken with infinite loops in the estimategas and call, as they essentially run without block gas limit. 

The fix was simple, just add the check against zero again. I kept the != nil, but might be removed.

### CODE REVIEW

File: cmd/rpcdaemon/commands/eth_call.go [hunk 1]
```diff
@@ -106,7 +106,7 @@ func (api *APIImpl) DoEstimateGas(ctx context.Context, args ethapi.CallArgs, blo
 		}
 	}
 	// Recap the highest gas allowance with specified gascap.
-	if gasCap != nil && hi > gasCap.Uint64() {
+	if gasCap != nil && gasCap.Uint64() != 0 && hi > gasCap.Uint64() {
```
Comment (mandrigin) [inline cmd/rpcdaemon/commands/eth_call.go:109]: One tiny nitpick that there should be IsZero() method on gasCap

Comment (3esmit) [reply cmd/rpcdaemon/commands/eth_call.go:109]: It gives me error when I use `gasCap.IsZero()`: `gasCap.IsZero undefined (type *big.Int has no field or method IsZero)`

Comment (AlexeyAkhunov) [reply cmd/rpcdaemon/commands/eth_call.go:109]: I with with the `*big.Int` the way to check for zero is `gasCap.Sign() == 0`, that works regardless of whether it fits into uint64 or not

Comment (3esmit) [reply cmd/rpcdaemon/commands/eth_call.go]: So for checking I than used gasCap.Sign() > 0, so in case o zero or negative value it would return false.

Comment (AlexeyAkhunov) [reply cmd/rpcdaemon/commands/eth_call.go]: Thank you! I will do a quick test a bit later and merge if it is ok
