### PR TITLE
Jump tables data race

### LINKED ISSUE #1237: EIPs enabling and hard forks are broken
There is a data race
```
WARNING: DATA RACE
Read at 0x00c000295508 by goroutine 100:
  github.com/ledgerwatch/turbo-geth/core/vm.enable2200()
      /mnt/sdb/go/src/github.com/ledgerwatch/sync/turbo-geth/core/vm/eips.go:108 +0x87
  github.com/ledgerwatch/turbo-geth/core/vm.EnableEIP()
      /mnt/sdb/go/src/github.com/ledgerwatch/sync/turbo-geth/core/vm/eips.go:43 +0xa6
  github.com/ledgerwatch/turbo-geth/core/vm.NewEVMInterpreter()
      /mnt/sdb/go/src/github.com/ledgerwatch/sync/turbo-geth/core/vm/interpreter.go:123 +0x124
  github.com/ledgerwatch/turbo-geth/core/vm.NewEVM()
      /mnt/sdb/go/src/github.com/ledgerwatch/sync/turbo-geth/core/vm/evm.go:175 +0x777
  github.com/ledgerwatch/turbo-geth/core/vm.TestEIP2200.func1()
      /mnt/sdb/go/src/github.com/ledgerwatch/sync/turbo-geth/core/vm/gas_table_test.go:109 +0x1097
  testing.tRunner()
      /snap/go/current/src/testing/testing.go:1127 +0x202

Previous write at 0x00c000295508 by goroutine 104:
  github.com/ledgerwatch/turbo-geth/core/vm.enable2200()
      /mnt/sdb/go/src/github.com/ledgerwatch/sync/turbo-geth/core/vm/eips.go:109 +0x159
  github.com/ledgerwatch/turbo-geth/core/vm.EnableEIP()
      /mnt/sdb/go/src/github.com/ledgerwatch/sync/turbo-geth/core/vm/eips.go:43 +0xa6
  github.com/ledgerwatch/turbo-geth/core/vm.NewEVMInterpreter()
      /mnt/sdb/go/src/github.com/ledgerwatch/sync/turbo-geth/core/vm/interpreter.go:123 +0x124
  github.com/ledgerwatch/turbo-geth/core/vm.NewEVM()
      /mnt/sdb/go/src/github.com/ledgerwatch/sync/turbo-geth/core/vm/evm.go:175 +0x777
  github.com/ledgerwatch/turbo-geth/core/vm.TestEIP2200.func1()
      /mnt/sdb/go/src/github.com/ledgerwatch/sync/turbo-geth/core/vm/gas_table_test.go:109 +0x1097
  testing.tRunner()
      /snap/go/current/src/testing/testing.go:1127 +0x202
```

The data race in tests can be solved easily, however, it shows that in `core/vm/interpreter.go` NewEVMInterpreter we don't deep-copying jump tables `JumpTable [256]*operation`. So any changes like enabling EIPs or hard forks will change original jump tables `core/vm/jump_table.go`:

```
var (
	frontierInstructionSet         = newFrontierInstructionSet()
	homesteadInstructionSet        = newHomesteadInstructionSet()
	tangerineWhistleInstructionSet = newTangerineWhistleInstructionSet()
	spuriousDragonInstructionSet   = newSpuriousDragonInstructionSet()
	byzantiumInstructionSet        = newByzantiumInstructionSet()
	constantinopleInstructionSet   = newConstantinopleInstructionSet()
	istanbulInstructionSet         = newIstanbulInstructionSet()
	yoloV1InstructionSet           = newYoloV1InstructionSet()
)
```

1. JumpTable is an array of ref types
2. Each operation includes a few ref types:
```
type operation struct {
	...
	execute     executionFunc
	...
	dynamicGas  gasFunc
	...
	memorySize memorySizeFunc
}
```

So once EIP or hard fork are enabled they will be enabled forever even in case of reorg to blocks without such EIPs or hardforks.

Some logs are here https://github.com/ledgerwatch/turbo-geth/commit/189dcbc0b54d49ccd8055a0161d0482f5abd6170

### PR DESCRIPTION
**Pull request by JekaMas**
closes #1237

also fixes a few data races in different parts of the code.

### CODE REVIEW

File: core/vm/interpreter.go [hunk 1]
```diff
@@ -118,15 +118,15 @@ func NewEVMInterpreter(evm *EVM, cfg Config) *EVMInterpreter {
 		jt = &frontierInstructionSet
 	}
 	if len(cfg.ExtraEips) > 0 {
-		jtCopy := *jt
+		jtCopy := jt.Clone()
```
Comment (AlexeyAkhunov) [inline core/vm/interpreter.go:121]: Why is this needed? Is jump table populated further from some other threads?

Comment (JekaMas) [reply core/vm/interpreter.go:121]: Not really, hovewer, jump tables are global variables and a bunch EIPs can be applied over this variables, changing them.

Comment (AlexeyAkhunov) [reply core/vm/interpreter.go:121]: I have a concern that this cloning will be happening at every transaction. We actually remove some kind of cloning like this before because it was taking a large percentage of time in the profiling

Comment (JekaMas) [reply core/vm/interpreter.go:121]: Will profile before and after the changes.

Comment (AlexeyAkhunov) [reply core/vm/interpreter.go:121]: I would not invest much into it. We definitely do not want to do this cloning, it has been shown in the past to be expensive. Let's rethink this fix as a whole, we can find a much better solution

Comment (JekaMas) [reply core/vm/interpreter.go]: Ok, I removed cloning. Could you take a look at it?

Comment (AlexeyAkhunov) [reply core/vm/interpreter.go]: Now I looked at it more closely. I think the reason you were  `ExtraEips` is currently only used in tests and in the `t8n` tool, and not in the actual instruction sets in production. In production those `jt` are are immutable once constructed. So I think the original data race probably occurred because tests were running in parallel. Now I see that your cloning solution, or removing the `t.Parallel()` would both do the trick. I would prefer just remove `t.Parallel()` to be honest, and remove rest of the code, I don't think it adds anything

Comment (JekaMas) [reply core/vm/interpreter.go]: Done
