### PR TITLE
Extract nonstandard APIs and introduce tg namespace

### LINKED ISSUE #1247: Custom RPC commands should be added to tg_ namespace
We should add non-standard RPC commands (such as the two `eth_getHeader*` commands and `eth_forkid` to a custom namespace.

Suggestion: `tg_`

1) look for other examples of incorrectly included commands in `eth_`
2) create new API namespace
3) move functions to `eth_tg.go`
4) add tests

### PR DESCRIPTION
**Pull request by JekaMas**
closes #1247

### CODE REVIEW

File: cmd/rpcdaemon/cli/config.go [hunk 1]
```diff
@@ -60,7 +60,7 @@ func RootCommand() (*cobra.Command, *Flags) {
 	rootCmd.PersistentFlags().IntVar(&cfg.HttpPort, "http.port", node.DefaultHTTPPort, "HTTP-RPC server listening port")
 	rootCmd.PersistentFlags().StringSliceVar(&cfg.HttpCORSDomain, "http.corsdomain", []string{}, "Comma separated list of domains from which to accept cross origin requests (browser enforced)")
 	rootCmd.PersistentFlags().StringSliceVar(&cfg.HttpVirtualHost, "http.vhosts", node.DefaultConfig.HTTPVirtualHosts, "Comma separated list of virtual hostnames from which to accept requests (server enforced). Accepts '*' wildcard.")
-	rootCmd.PersistentFlags().StringSliceVar(&cfg.API, "http.api", []string{"eth"}, "API's offered over the HTTP-RPC interface")
+	rootCmd.PersistentFlags().StringSliceVar(&cfg.API, "http.api", []string{"eth", "tg"}, "API's offered over the HTTP-RPC interface")
```
Comment (tjayrush) [inline cmd/rpcdaemon/cli/config.go:63]: Do we want to make this part of the default? Probably not. In fact, the default should probably be eth, web3 and net (which are the standard namespaces on other nodes).

Comment (JekaMas) [reply cmd/rpcdaemon/cli/config.go:63]: I agree, `tg` calls at the moment are quite specific also. However, the problem is that we need `tg_forks` by default for the sentry. Also `tg` at the moment is more like an extension of `eth`.

File: cmd/rpcdaemon/commands/tg_block.go [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+
+	"github.com/ledgerwatch/turbo-geth/common"
+	"github.com/ledgerwatch/turbo-geth/core/rawdb"
+	"github.com/ledgerwatch/turbo-geth/core/types"
+	"github.com/ledgerwatch/turbo-geth/rpc"
+)
+
+// GetHeaderByNumber returns a block's header by number
+func (api *TgImpl) GetHeaderByNumber(ctx context.Context, number rpc.BlockNumber) (*types.Header, error) {
+	tx, err := api.dbReader.Begin(ctx)
```
Comment (AlexeyAkhunov) [inline cmd/rpcdaemon/commands/tg_block.go:15]: Can you please change here (and below) to `tx, err := api.db.Begin(ctx, nil, false)`. That open read-only transaction instead of writeable one. It does not matter for the remove KV, but it does matter with `--chaindata` option

Comment (JekaMas) [reply cmd/rpcdaemon/commands/tg_block.go:15]: Got it, thank you.
