### PR TITLE
Remove `Copy` from `IntraBlockState` and add thread synchronization.

### LINKED ISSUE #130: Remove Copy member functions from IntraBlockState
Since there is no efficient way of copying intra-block-state (for the purpose of concurrent access, for example), it makes sense to remove `Copy` functions rather than leaving them incorrect, but present.
This will also illuminate the need to fix the miner code

### PR DESCRIPTION
**Pull request by mandrigin**
fixes #130

### CODE REVIEW

**Comment by mandrigin** [comment]
@AlexeyAkhunov I've fixed the PR according to (my understanding of) your comments :-D

File: miner/worker.go [hunk 1]
```diff
@@ -255,7 +255,8 @@ func (w *worker) pending() (*types.Block, *state.IntraBlockState, *state.TrieDbS
 	if w.snapshotState == nil {
 		return nil, nil, nil
 	}
-	return w.snapshotBlock, w.snapshotState.Copy(), w.snapshotTds.Copy()
+	// FIXME: restore miner code
```
Comment (mandrigin) [inline miner/worker.go]: add the GH issue number

Comment (mandrigin) [reply miner/worker.go]: done
